function sh_m
    form = figure(...
        'units','pixels',...
        'position',[50,50,1000,600],...
        'menubar','none');
    out = uitable(...
        'RowName',[],...
        'position',[330,510,650,60]);
    set(out,'data',zeros(1,100));
    out.ColumnEditable = true;
    out.Data(1,2) = 2;
end